### ISSUE TITLE
CI uses an old `stack` version

### ISSUE THREAD

**Issue by DiegoDiverio** [channable/icepeak#105]
Looking at these [CI messages](https://channable.semaphoreci.com/jobs/492e30e3-b933-494c-9e54-6c275fd16182#L604), I stumbled upon warnings regarding the version of `stack` we use.

We could upgrade to a newer version. I use 2.9.1 on my system, for example.

**Comment by rkrzr** [comment]
We should just move icepeak over to cabal (with nix), since we're also doing that with our other projects now.

**Comment by robbert-vdh** [comment]
Since I've already figured everything out for the Hoff repo anyways, I can do the same thing for Icepeak when I have some downtime. With Stack HLS now oftne complains about missing or hidden modules when editing either the tests or the executable, so having that fixed would be great.

**Comment by rkrzr** [comment]
@robbert-vdh is this issue fixed with your PR in https://github.com/channable/icepeak/pull/116 ?

**Comment by robbert-vdh** [comment]
Indeed, we no longer use stack. You can't use an out of date version of something if you don't use it at all!
