### ISSUE TITLE
Allow requests with some sort of durability guarantee

### ISSUE THREAD

**Issue by fatho** [channable/icepeak#25]
Currently, requests to the HTTP API post the command to the core queue and then immediately return. This could lead to a situation where a `GET` following a `PUT` returns stale data.

The proposal is to add a `durable` URL parameter that causes `PUT` and `DELETE` requests to wait until the modification has been applied to the data store. The easiest way is probably to create a new MVar in the request and pass it along the modification in the corresponding command:

https://github.com/channable/icepeak/blob/e6cfbec09c2e5dde0e6972702ade2ffdc99b3d04/server/src/Core.hs#L50

would become

```Haskell
 | Modify Modification (Maybe (MVar ()))
```

The `Nothing` case would behave as before, in the `Just` case, the `MVar` is filled after the modification has been processed and the request handler blocks with `takeMVar`.

**Comment by ruuda** [comment]
Here’s a good overview of how to write data to disk in a way that ensures consistency: https://danluu.com/file-consistency/.

**Comment by rkrzr** [comment]
We now support requests with a strong(er) durability guarantee. This was added in https://github.com/channable/icepeak/pull/27.
