### ISSUE TITLE
Deadlock when command queue is full and posting an update to a client failed

### ISSUE THREAD

**Issue by fatho** [channable/icepeak#40]
Every modification to the Icepeak database is broadcast to all clients *that are subscribed on the specific path or one of its parents (EDIT)*. However, there are no exception handlers in the websocket sending code. Therefore, when sending an update fails, the whole update thread crashes. In that case, the main thread logs the exception and cleanly shuts down icepeak.

Now comes the part with the deadlock:

1. The Icepeak `Core` thread posts updates to the websocket update thread through a bounded queue, and blocks when it is full. In that case, it won't process any further commands until it managed to post the update on the queue.
2. When the websocket thread crashes, there is no one reading from the update queue, therefore, the `Core` thread remains stuck forever.
3. The main thread tries to cleanly shut down Icepeak by posting a `Stop` command to the `Core`'s command queue and waiting for the `Core` to exit. However, because the `Core` is currently stuck waiting on the update queue, it won't process the stop message, and eventually also reject all incoming requests, because the command queue also fills up.

Solution:

Catch exceptions while sending updates and log and/or update Prometheus metric

**Comment by rkrzr** [comment]
> Every modification to the Icepeak database is broadcast to all clients.

Small correction: Clients can subscribe to specific paths, and they will get updates only for modifications that fall below that path. Only clients that subscribe to the root path (and that have permission to do so) will get all updates.

For the rest, I fully agree with your proposed fix. Nice catch.

**Comment by fatho** [comment]
I'm actually not sure whether we would want to log this. Clients coming and going is a usual process, and just because it happens while currently trying to send something doesn't mean it is more noteworthy than a client leaving while not sending.

Also, we do not log other connection errors with subscribed websocket clients.

**Comment by rkrzr** [comment]
This was fixed in https://github.com/channable/icepeak/pull/41
