### ISSUE TITLE
Icepeak does not push non-root updates to the WebSocket clients

### ISSUE THREAD

**Issue by rightfold** [channable/icepeak#5]
For example, `PUT /foo/bar` does not cause the client to receive the update. Only `PUT /` does.

**Comment by rightfold** [comment]
It seems to be a more general issue: Icepeak only notifies changes to the direct subscribee. It should also notify anything that is subscribed to a direct or indirect parent.

**Comment by rkrzr** [comment]
Could you have a look at this @rightfold ?
